### ISSUE TITLE
"pip install rvc3-python"  Error.

### ISSUE THREAD

**Issue by GradyM2M** [petercorke/RVC3-python#1]
hi, Dear Mr. petercorke, when I run the command "pip install rvc3-python", I get the following error:

(venv) grady@T480:~$ pip install rvc3-python
ERROR: Could not find a version that satisfies the requirement rvc3-python (from versions: none)
ERROR: No matching distribution found for rvc3-python

How should I solve this problem?

**Comment by peter-pri** [comment]
Hi GradyM2M,
updated instructions can fe found at:
https://pypi.org/project/roboticstoolbox-python/
e.g. "pip3 install roboticstoolbox-python"

**Comment by GradyM2M** [comment]
@peter-pri Hi peter-pri,
I found the “rvc3python” package in Pycharm, but I haven't downloaded and used it yet.

**Comment by petercorke** [comment]
As the README states this is a work in progress.  It needs a lot of polishing but now that the book manuscript is done I get the code base into shape.

**Comment by peter-pri** [comment]
Hi Peter,
I am happy to hear that. I will definitely by a  copy of your book, as soon it is availalble. I have got an automatic e-mail from your e-mail account at QUT, good look at the antarctic.
Shall I write issues for the "robotics-toolbox-python" repository, or shall I wail until next (beta-)release ?
Kind regards,
Peter
