### ISSUE TITLE
app.ipynb -> ModuleNotFoundError: No module named 'ipympl'

### ISSUE THREAD

**Issue by dblanding** [petercorke/RVC3-python#10]
I get the ModuleNotFoundError when I run the very first code block of app.ipynb as a jupyter notebook on Ubuntu 22.04 

The error is resolved by commenting out the line
`%matplotlib ipympl`
and substituted the line
`import matplotlib as ipympl`

The code block then runs but with the following warning:
```
Not running on CoLab

/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
```

**Comment by petercorke** [comment]
I've tidied up this notebook a bit, making the figure creation better.

Notebooks and matplotlib figures are very painful, and very dependent on the OS and specific versions of installed packages.
