### ISSUE TITLE
AttributeError: 'ReedsSheppPlanner' object has no attribute 'curvature'

### ISSUE THREAD

**Issue by dblanding** [petercorke/RVC3-python#11]
I get the above error when running code from section 5.6.2
within an IPython session (after running `rvctool`).
```
qs = (0, 0, pi/2);
qg = (1, 0, pi/2);
rs = ReedsSheppPlanner(curvature=1)
path, status = rs.query(qs, qg)
```
I am using Ubuntu 22.04
The Dubins Planner works OK and I get the 3D interactive plot.
The odd thing is that the Reeds-Shepp planner worked once and now it won't work again. I always get this error !?!

[error.txt](https://github.com/petercorke/RVC3-python/files/13762371/error.txt)

**Comment by petercorke** [comment]
Yep, the error only happens when you stringify the object, happens by default at line 3 when using `rvctool`.  This fix will go out in the next minor release, will try to patch all the extant issues before I push it.
