### ISSUE TITLE
page 222, equation 6.22, 3rd edition

### ISSUE THREAD

**Issue by ryanyu512** [petercorke/RVC3-python#15]
Yz = [1_m*m, 0_m*x; 
         Gx, 0_2*(M-3), Gz)

If M = 0, then M - 3 is negative. It seems confusing

**Comment by petercorke** [comment]
Thanks for picking this up.  This is insertion Jacobian for the SLAM case, for the landmark-only case there should be no $`{\bf G}_x`$ and the zeros after it should be $`{\bf 0}_{2 \times M}`$
