### ISSUE TITLE
dependency problem

### ISSUE THREAD

**Issue by machine85** [petercorke/RVC3-python#4]
Hello,
i found that the packages bdsim and roboticstoolbox-python depend on the progress package,
the progress package is updated only up to python3.6:
https://pypi.org/project/progress/

most of the os today have python3.10

thank you for your help.

**Comment by petercorke** [comment]
Is this actually causing an issue?  I'm using it with Py 3.9 to 3.11 without issue.

**Comment by machine85** [comment]
Thank you sir.

‫בתאריך יום א׳, 9 ביולי 2023 ב-11:44 מאת ‪Peter Corke‬‏ <‪
***@***.***‬‏>:‬

**Comment by petercorke** [comment]
Since there is no impact on behaviour of bdsim I'm closing this.
