### ISSUE TITLE
Problem with launching rvctool 

### ISSUE THREAD

**Issue by followthwhiterabbit** [petercorke/RVC3-python#7]
I was running rvctool until recently but this time i had problem with possible conflicts regarding matplotlib, but looks like there isn't any conflict with matplotlib at all. I tried to execute it from ~/.local/bin but it didn't work either. Then i screwed it up and deleted rvctool from ~/.local/bin/ and tried to install again. Looks like all requirements are already satisfied without any possibility of running the program again. 

![Screenshot from 2023-10-27 02-22-05](https://github.com/petercorke/RVC3-python/assets/62688580/dcd4714a-f5a4-43dd-866f-0f276a851ff4)

Now, i even don't have where i can find the executable in the ./local/bin file. I have been following the book for a while now for my thesis, this is a major drawback. 

Traceback (most recent call last):
  File "/home/kaan/.local/bin/rvctool", line 5, in <module>
    from RVC3.bin.rvctool import main
  File "/home/kaan/.local/lib/python3.10/site-packages/RVC3/bin/rvctool.py", line 41, in <module>
    import matplotlib.pyplot as plt  # lgtm [py/unused-import]
  File "/home/kaan/.local/lib/python3.10/site-packages/matplotlib/pyplot.py", line 66, in <module>
    from matplotlib.figure import Figure, FigureBase, figaspect
  File "/home/kaan/.local/lib/python3.10/site-packages/matplotlib/figure.py", line 43, in <module>
    from matplotlib import _blocking_input, backend_bases, _docstring, projections
  File "/home/kaan/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py", line 58, in <module>
    from mpl_toolkits.mplot3d import Axes3D
  File "/usr/lib/python3/dist-packages/mpl_toolkits/mplot3d/__init__.py", line 1, in <module>
    from .axes3d import Axes3D
  File "/usr/lib/python3/dist-packages/mpl_toolkits/mplot3d/axes3d.py", line 23, in <module>
    from matplotlib import _api, cbook, docstring, _preprocess_data
ImportError: cannot import name 'docstring' from 'matplotlib' (/home/kaan/.local/lib/python3.10/site-packages/matplotlib/__init__.py)

**Comment by petercorke** [comment]
Sorry to be slow, I've been away on holiday.  The simplest option is to cut loose from rvctool, you can do everything from the standard Python REPL or Jupyter, you just have to explicitly do some imports:
```
    import math
    import numpy as np
    from scipy import linalg, optimize
    import matplotlib.pyplot as plt
    from spatialmath import *
    from spatialmath.base import *
    from spatialmath.base import sym
    from spatialgeometry import *
    from roboticstoolbox import *
    from machinevisiontoolbox import *
    import machinevisiontoolbox.base as mvb
    
    # useful variables
    from math import pi
```
or whatever subset is relevant to you.  

`rvctool` was meant to make life easy, but if it's tripping you up move on.  Or you can make individual scripts that use the toolbox and run them as you need to.


To get back to where you were, you might need to uninstall and reinstall.  It doesn't look you are using Conda, but I'd highly recommend it.  I was very resistant for a long time, but it really does make life easier.  You can just wipe out your RVC3 environment and reinstall, while leaving all other Python environments intact.
